
import { Artist, Genre, Gender, Theme, Badge } from './types';

// === CONQUISTAS ===
export const BADGES: Badge[] = [
  {
    id: 'veteran',
    name: 'Veterano',
    description: 'Jogue 50 partidas.',
    icon: '🎖️',
    condition: (u) => u.stats.totalMatches >= 50
  },
  {
    id: 'winner_bronze',
    name: 'Vencedor Nato',
    description: 'Vença 10 partidas.',
    icon: '🥉',
    condition: (u) => u.stats.totalWins >= 10
  },
  {
    id: 'winner_gold',
    name: 'Campeão Supremo',
    description: 'Vença 100 partidas.',
    icon: '🏆',
    condition: (u) => u.stats.totalWins >= 100
  },
  {
    id: 'rich',
    name: 'Ostentação',
    description: 'Acumule 1000 moedas no total.',
    icon: '💰',
    condition: (u) => u.stats.totalCoinsEarned >= 1000
  },
  {
    id: 'survivor',
    name: 'Sobrevivente',
    description: 'Chegue à rodada 10 no modo Sobrevivência.',
    icon: '🧟',
    condition: (u) => u.stats.highestRoundSurvival >= 10
  },
  {
    id: 'king_sertanejo',
    name: 'Rei do Sertanejo',
    description: 'Vença 5 partidas de Sertanejo.',
    icon: '🤠',
    condition: (u) => (u.stats.genreCounts[Genre.SERTANEJO] || 0) >= 5
  },
  {
    id: 'pop_star',
    name: 'Pop Star',
    description: 'Vença 5 partidas de Pop BR.',
    icon: '🎤',
    condition: (u) => (u.stats.genreCounts[Genre.POP_BR] || 0) >= 5
  }
];

// === LOJA ===
export const SHOP_ITEMS = [
  { id: 'hint', name: 'Dica Extra', icon: '💡', price: 100, type: 'consumable', key: 'hints', desc: '+1 Dica no estoque' },
  { id: 'skip', name: 'Troca Extra', icon: '🔄', price: 150, type: 'consumable', key: 'skips', desc: '+1 Troca no estoque' },
  { id: 'life', name: 'Vida Extra', icon: '❤️', price: 300, type: 'consumable', key: 'lives', desc: '+1 Vida (Survival)' },
];

export const THEMES: Theme[] = [
  {
    id: 'default',
    name: 'Clássico Pop',
    minLevel: 1,
    background: 'bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-pink-400 via-purple-300 to-indigo-400',
    buttonGradient: 'bg-gradient-to-b from-pink-500 to-pink-700 border-b-4 border-pink-900 shadow-xl shadow-pink-500/30 hover:-translate-y-0.5 active:translate-y-1 active:border-b-0 active:shadow-none',
    accentColor: 'text-pink-900',
    emoji: '🎸'
  },
  {
    id: 'ocean',
    name: 'Vibe Oceano',
    minLevel: 3,
    background: 'bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-cyan-400 via-blue-300 to-blue-500',
    buttonGradient: 'bg-gradient-to-b from-cyan-500 to-blue-600 border-b-4 border-blue-800 shadow-xl shadow-blue-500/30 hover:-translate-y-0.5 active:translate-y-1 active:border-b-0 active:shadow-none',
    accentColor: 'text-blue-900',
    emoji: '🌊'
  },
  {
    id: 'sunset',
    name: 'Pôr do Sol',
    minLevel: 5,
    background: 'bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-orange-300 via-rose-300 to-red-400',
    buttonGradient: 'bg-gradient-to-b from-orange-500 to-rose-600 border-b-4 border-rose-800 shadow-xl shadow-rose-500/30 hover:-translate-y-0.5 active:translate-y-1 active:border-b-0 active:shadow-none',
    accentColor: 'text-rose-900',
    emoji: '🌅'
  },
  {
    id: 'nature',
    name: 'Floresta Zen',
    minLevel: 10,
    background: 'bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-emerald-300 via-green-200 to-teal-400',
    buttonGradient: 'bg-gradient-to-b from-emerald-500 to-teal-600 border-b-4 border-teal-800 shadow-xl shadow-teal-500/30 hover:-translate-y-0.5 active:translate-y-1 active:border-b-0 active:shadow-none',
    accentColor: 'text-emerald-900',
    emoji: '🌿'
  },
  {
    id: 'royal',
    name: 'Luxo Dourado',
    minLevel: 20,
    background: 'bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-yellow-200 via-amber-100 to-yellow-500',
    buttonGradient: 'bg-gradient-to-b from-yellow-500 to-amber-600 border-b-4 border-amber-800 shadow-xl shadow-amber-500/30 hover:-translate-y-0.5 active:translate-y-1 active:border-b-0 active:shadow-none text-white',
    accentColor: 'text-amber-900',
    emoji: '👑'
  },
  {
    id: 'dark',
    name: 'Modo Noturno',
    minLevel: 30,
    background: 'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-700 via-slate-900 to-black',
    buttonGradient: 'bg-gradient-to-b from-purple-600 to-slate-800 border-b-4 border-black shadow-xl shadow-purple-900/50 hover:-translate-y-0.5 active:translate-y-1 active:border-b-0 active:shadow-none',
    accentColor: 'text-purple-400',
    emoji: '🌙'
  }
];

export const AVATARS = [
  '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐨', '🐯', 
  '🦁', '🐮', '🐷', '🐸', '🐵', '🐔', '🐧', '🐦', '🐤', '🦆',
  '🦅', '🦉', '🦇', '🐺', '🐗', '🐴', '🦄', '🐝', '🐛', '🦋',
  '🐌', '🐞', '🐜', '🕷', '🐢', '🐍', '🦎', '🐙', '🦑', '🦐',
  '🦞', '🦀', '🐡', '🐠', '🐟', '🐬', '🐳', '🐋', '🦈', '🐊',
  '🐅', '🐆', '🦓', '🦍', '🦧', '🐘', '🦛', '🦏', '🐪', '🐫',
  '🦒', '🦘', '🐃', '🐂', '🐄', '🐎', '🐖', '🐏', '🐑', '🦙',
  '🐐', '🦌', '🐕', '🐩', '🦮', '🐕‍🦺', '🐈', '🐈‍⬛', '🐓', '🦃',
  '🦚', '🦜', '🦢', '🦩', '🕊', '🐇', '🦝', '🦨', '🦡', '🦦',
  '🦥', '🐁', '🐀', '🐿', '🦔', '🐾', '🐉', '🐲', '🌵', '🎄',
  '🌲', '🌳', '🌴', '🌱', '🌿', '☘', '🍀', '🎍', '🎋', '🍃',
  '🍂', '🍁', '🍄', '🌾', '💐', '🌷', '🌹', '🥀', '🌺', '🌸',
  '🌼', '🌻', '🌞', '🌝', '🌛', '🌜', '🌚', '🌕', '🌖', '🌗',
  '🌘', '🌑', '🌒', '🌓', '🌔', '🌙', '🌎', '🌍', '🌏', '🪐',
  '💫', '⭐️', '🌟', '✨', '⚡️', '☄', '💥', '🔥', '🌪', '🌈',
  '☀️', '🌤', '⛅️', '🌥', '☁️', '🌦', '🌧', '⛈', '🌩', '🌨',
  '❄️', '☃️', '⛄️', '🌬', '💨', '💧', '💦', '☔️', '☂️', '🌊',
  '🎸', '🎹', '🎺', '🎻', '🥁', '🎤', '🎧', '🎼', '🎭', '🎨'
];

export const ARTIST_DB: Artist[] = [
  // === SERTANEJO (FEMININO) ===
  { name: 'Marília Mendonça', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Simone Mendes', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Ana Castela', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Naiara Azevedo', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Lauana Prado', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Yasmin Santos', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Paula Fernandes', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Mari Fernandez', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Luiza Martins', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Brisa Star', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Roberta Miranda', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Paula Mattos', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Gaby Amarantos', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Solange Almeida', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Walkyria Santos', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Priscila Senna', cat: Genre.SERTANEJO, gender: Gender.F },
  { name: 'Raphaela Santos', cat: Genre.SERTANEJO, gender: Gender.F },

  // === SERTANEJO (MASCULINO) ===
  { name: 'Gusttavo Lima', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Luan Santana', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Michel Teló', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Leonardo', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Daniel', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Zé Felipe', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Murilo Huff', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Felipe Araújo', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Gustavo Mioto', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Eduardo Costa', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Tierry', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'João Gomes', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Tarcísio do Acordeon', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Nattan', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Vitor Fernandes', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Luan Pereira', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Tiago Iorc', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Xand Avião', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Wesley Safadão', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Tayrone', cat: Genre.SERTANEJO, gender: Gender.M },
  { name: 'Pablo', cat: Genre.SERTANEJO, gender: Gender.M },

  // === SERTANEJO (DUPLAS/GRUPOS) ===
  { name: 'Jorge e Mateus', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Henrique e Juliano', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Zé Neto e Cristiano', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Matheus e Kauan', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Maiara e Maraisa', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Israel e Rodolffo', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Bruno e Marrone', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Chitãozinho e Xororó', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Hugo e Guilherme', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Clayton e Romário', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Guilherme e Benuto', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Edson e Hudson', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Zezé Di Camargo e Luciano', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Leandro e Leonardo', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Rick e Renner', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Marcos e Belutti', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Diego e Victor Hugo', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'João Bosco e Vinícius', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Jads e Jadson', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Fernando e Sorocaba', cat: Genre.SERTANEJO, gender: Gender.G },
  { name: 'Thaeme e Thiago', cat: Genre.SERTANEJO, gender: Gender.G },

  // === PAGODE/SAMBA ===
  { name: 'Thiaguinho', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Ferrugem', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Dilsinho', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Péricles', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Belo', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Mumuzinho', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Xande de Pilares', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Diogo Nogueira', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Zeca Pagodinho', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Tiee', cat: Genre.PAGODE, gender: Gender.M },
  { name: 'Marvvila', cat: Genre.PAGODE, gender: Gender.F },
  { name: 'Gica', cat: Genre.PAGODE, gender: Gender.F },
  { name: 'Leci Brandão', cat: Genre.PAGODE, gender: Gender.F },
  { name: 'Alcione', cat: Genre.PAGODE, gender: Gender.F },
  { name: 'Maria Rita', cat: Genre.PAGODE, gender: Gender.F },
  { name: 'Sorriso Maroto', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Menos é Mais', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Turma do Pagode', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Exaltasamba', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Jeito Moleque', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Pixote', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Raça Negra', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Só Pra Contrariar', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Grupo Revelação', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Kamisa 10', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Di Propósito', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Molejo', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Fundo de Quintal', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Art Popular', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Katinguelê', cat: Genre.PAGODE, gender: Gender.G },
  { name: 'Karametade', cat: Genre.PAGODE, gender: Gender.G },

  // === POP/FUNK BR ===
  { name: 'Anitta', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Luísa Sonza', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Iza', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Gloria Groove', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Ludmilla', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Pocah', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Lexa', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Pabllo Vittar', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Marina Sena', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Duda Beat', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Rebecca', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'Tati Quebra Barraco', cat: Genre.POP_BR, gender: Gender.F },
  { name: 'MC Cabelinho', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'Kevin o Chris', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'Pedro Sampaio', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC Daniel', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC Ryan SP', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'L7NNON', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'Jão', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'Xamã', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'Matuê', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'Filipe Ret', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'Orochi', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'Teto', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'WIU', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC IG', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC Hariel', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC Livinho', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC Kevin', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC Bin Laden', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'Veigh', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC Poze do Rodo', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC Don Juan', cat: Genre.POP_BR, gender: Gender.M },
  { name: 'MC Pedrinho', cat: Genre.POP_BR, gender: Gender.M },

  // === GOSPEL ===
  { name: 'Aline Barros', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Gabriela Rocha', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Isadora Pompeo', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Bruna Karla', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Cassiane', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Damares', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Fernanda Brum', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Eyshila', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Soraya Moraes', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Julliany Souza', cat: Genre.GOSPEL, gender: Gender.F },
  { name: 'Fernandinho', cat: Genre.GOSPEL, gender: Gender.M },
  { name: 'Anderson Freire', cat: Genre.GOSPEL, gender: Gender.M },
  { name: 'Thalles Roberto', cat: Genre.GOSPEL, gender: Gender.M },
  { name: 'Kleber Lucas', cat: Genre.GOSPEL, gender: Gender.M },
  { name: 'Regis Danese', cat: Genre.GOSPEL, gender: Gender.M },
  { name: 'Preto no Branco', cat: Genre.GOSPEL, gender: Gender.G },
  { name: 'Morada', cat: Genre.GOSPEL, gender: Gender.G },
  { name: 'Casa Worship', cat: Genre.GOSPEL, gender: Gender.G },
  { name: 'Diante do Trono', cat: Genre.GOSPEL, gender: Gender.G },
  { name: 'Kemuel', cat: Genre.GOSPEL, gender: Gender.G },
  { name: 'Voz da Verdade', cat: Genre.GOSPEL, gender: Gender.G },

  // === INTERNACIONAL ===
  { name: 'Bruno Mars', cat: Genre.POP_INTL, gender: Gender.M },
  { name: 'The Weeknd', cat: Genre.POP_INTL, gender: Gender.M },
  { name: 'Justin Bieber', cat: Genre.POP_INTL, gender: Gender.M },
  { name: 'Ed Sheeran', cat: Genre.POP_INTL, gender: Gender.M },
  { name: 'Post Malone', cat: Genre.POP_INTL, gender: Gender.M },
  { name: 'Harry Styles', cat: Genre.POP_INTL, gender: Gender.M },
  { name: 'Drake', cat: Genre.POP_INTL, gender: Gender.M },
  { name: 'Travis Scott', cat: Genre.POP_INTL, gender: Gender.M },
  { name: 'Beyoncé', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Taylor Swift', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Dua Lipa', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Adele', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Rihanna', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Ariana Grande', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Billie Eilish', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Lady Gaga', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Miley Cyrus', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Katy Perry', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'SZA', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Olivia Rodrigo', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Doja Cat', cat: Genre.POP_INTL, gender: Gender.F },
  { name: 'Coldplay', cat: Genre.POP_INTL, gender: Gender.G },
  { name: 'Maroon 5', cat: Genre.POP_INTL, gender: Gender.G },
  { name: 'Imagine Dragons', cat: Genre.POP_INTL, gender: Gender.G },
  { name: 'Arctic Monkeys', cat: Genre.POP_INTL, gender: Gender.G },
  { name: 'OneRepublic', cat: Genre.POP_INTL, gender: Gender.G },
  { name: 'Linkin Park', cat: Genre.POP_INTL, gender: Gender.G },
  { name: 'Queen', cat: Genre.POP_INTL, gender: Gender.G },
  { name: 'The Beatles', cat: Genre.POP_INTL, gender: Gender.G },
  { name: 'Twenty One Pilots', cat: Genre.POP_INTL, gender: Gender.G },

  // === ROCK/MPB/OUTROS ===
  { name: 'Legião Urbana', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Charlie Brown Jr.', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Skank', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Jota Quest', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Capital Inicial', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Titãs', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Os Paralamas do Sucesso', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'O Rappa', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Cidade Negra', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Raimundos', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Mamonas Assassinas', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Los Hermanos', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Roupa Nova', cat: Genre.ROCK_MPB, gender: Gender.G },
  { name: 'Pitty', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Rita Lee', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Cássia Eller', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Elis Regina', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Maria Bethânia', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Gal Costa', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Adriana Calcanhotto', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Vanessa da Mata', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Céu', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Nando Reis', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Djavan', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Cazuza', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Lulu Santos', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Caetano Veloso', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Gilberto Gil', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Seu Jorge', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Baco Exu do Blues', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Liniker', cat: Genre.ROCK_MPB, gender: Gender.F },
  { name: 'Tim Maia', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Milton Nascimento', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Chico Buarque', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Emicida', cat: Genre.ROCK_MPB, gender: Gender.M },
  { name: 'Criolo', cat: Genre.ROCK_MPB, gender: Gender.M },

  // === FLASHBACK (NOVA CATEGORIA) ===
  { name: 'Michael Jackson', cat: Genre.FLASHBACK, gender: Gender.M },
  { name: 'Madonna', cat: Genre.FLASHBACK, gender: Gender.F },
  { name: 'Cyndi Lauper', cat: Genre.FLASHBACK, gender: Gender.F },
  { name: 'Whitney Houston', cat: Genre.FLASHBACK, gender: Gender.F },
  { name: 'Elton John', cat: Genre.FLASHBACK, gender: Gender.M },
  { name: 'Stevie Wonder', cat: Genre.FLASHBACK, gender: Gender.M },
  { name: 'ABBA', cat: Genre.FLASHBACK, gender: Gender.G },
  { name: 'Bee Gees', cat: Genre.FLASHBACK, gender: Gender.G },
  { name: 'a-ha', cat: Genre.FLASHBACK, gender: Gender.G },
  { name: 'Bon Jovi', cat: Genre.FLASHBACK, gender: Gender.G },
  { name: 'Guns N Roses', cat: Genre.FLASHBACK, gender: Gender.G },
  { name: 'U2', cat: Genre.FLASHBACK, gender: Gender.G },
  { name: 'Prince', cat: Genre.FLASHBACK, gender: Gender.M },
  { name: 'David Bowie', cat: Genre.FLASHBACK, gender: Gender.M },
  { name: 'Tina Turner', cat: Genre.FLASHBACK, gender: Gender.F },

  // === TIKTOK / VIRAIS (NOVA CATEGORIA) ===
  { name: 'Chico Moedas', cat: Genre.TIKTOK, gender: Gender.M },
  { name: 'Tubarão Te Amo', cat: Genre.TIKTOK, gender: Gender.G },
  { name: 'Treyce', cat: Genre.TIKTOK, gender: Gender.F },
  { name: 'Melody', cat: Genre.TIKTOK, gender: Gender.F },
  { name: 'Os Barões da Pisadinha', cat: Genre.TIKTOK, gender: Gender.G },
  { name: 'Nadson O Ferinha', cat: Genre.TIKTOK, gender: Gender.M },
  { name: 'Manu Bahtidão', cat: Genre.TIKTOK, gender: Gender.F },
  { name: 'Kadu Martins', cat: Genre.TIKTOK, gender: Gender.M },
  { name: 'Felipe Amorim', cat: Genre.TIKTOK, gender: Gender.M },
  { name: 'Rogerinho', cat: Genre.TIKTOK, gender: Gender.M },
  { name: 'Léo Santana', cat: Genre.TIKTOK, gender: Gender.M }, // Zona de Perigo
];

export const AUDIO_LIMIT_SECONDS = 5;
